apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-img
  labels:
    k8s-app: color-img
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: color-img
  template:
    metadata: 
      labels:
        k8s-app: color-img
    spec:
      containers:
      - name: color-img-pod
        image: nagadomi/torch7
        command: ["sleep", "infinity"]
        resources:
          limits:
            #nvidia.com/gpu: "1"
            memory: "8G"
            cpu: "1"
          requests:
             memory: "8G"
             cpu: "1"
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: nvidia.com/gpu.product
      #          operator: In
      #          values:
      #          - NVIDIA-A10
                #- Tesla-V100-SXM2-32GB